### ISSUE TITLE
User class filter not working

### ISSUE THREAD

**Issue by majkrebs** [bobcozzi/wrkusr#1]
The user class filter does not work. Looks like all the actual filtering code was left out.

**Comment by bobcozzi** [comment]
Thanks. It looks like the following code needs to be added to the DECLARE U2 CURSOR FOR... statement on the WHERE clause:
  `and   
 UI.USER_CLASS_NAME =
      CASE WHEN :filters.usrclass = ''
        THEN UI.USER_CLASS_NAME
        ELSE :filters.usrclass
     end` 
I will update the build shortly. But you can just cut/paste this into your copy.
